### ISSUE TITLE
Pytorch's Automatic Mixed Precision (AMP) is not supported for non-uniform field types.

### ISSUE THREAD

**Issue by LVeefkind** [QUVA-Lab/escnn#38]
Currently, [Automatic Mixed Precision (AMP)](https://pytorch.org/tutorials/recipes/recipes/amp_recipe.html) is not supported for non-uniform field types. This is the script used to replicate the problem: 

```
from escnn import group
from escnn import gspaces
from escnn import nn
import torch
from functools import partial


class O2SteerableCNNGated(torch.nn.Module):
    def __init__(self):
        super(O2SteerableCNNGated, self).__init__()

        self.act_r2 = gspaces.flipRot2dOnR2(N=-1)

        self.in_type = nn.FieldType(self.act_r2, [self.act_r2.trivial_repr])

        self.upsample = nn.R2Upsampling(self.in_type, size=(29, 29))

        self.mask = nn.MaskModule(self.in_type, 29, margin=1)

        channels = 12
        L = 4
        ################# This doesn't work
        out_type = nn.FieldType(
            self.act_r2,
            channels * [self.act_r2.irreps[0] for _ in range(L + 1)]
            + channels * [self.act_r2.irreps[i] for i in range(L + 1)],
        )

        ############# This does, since the field type is uniform
        # out_type = nn.FieldType(
        #     self.act_r2,
        #     channels * [self.act_r2.irreps[0]]
        #     + channels
        #     * [group.directsum([self.act_r2.irreps[i] for i in range(L + 1)])],
        # )

        self.block_1 = nn.SequentialModule(
            nn.R2Conv(self.in_type, out_type, kernel_size=5, padding=1),
        )

    def forward(self, x):
        x = self.in_type(x)
        x = self.upsample(x)
        x = self.mask(x)
        x = self.block_1(x)

        return x


if __name__ == "__main__":
    device = "cuda"
    USE_AMP = True

    o2_gated_nonlinearity = O2SteerableCNNGated().to(device)
    data = torch.randn(128, 1, 28, 28).to(device)
    with torch.autocast(device_type=device, dtype=torch.float16, enabled=USE_AMP):
        o2_gated_nonlinearity(data)
```

Running the script results in the following error:

```
/home/lars/miniconda3/envs/thesis/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525541990/work/aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/home/lars/Studie/Thesis/experimenting_code/old_tests/bug_report.py", line 67, in <module>
    o2_gated_nonlinearity(data)
  File "/home/lars/miniconda3/envs/thesis/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lars/Studie/Thesis/experimenting_code/old_tests/bug_report.py", line 55, in forward
    x = self.block_1(x)
  File "/home/lars/miniconda3/envs/thesis/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lars/miniconda3/envs/thesis/lib/python3.10/site-packages/escnn/nn/modules/sequential_module.py", line 88, in forward
    x = m(x)
  File "/home/lars/miniconda3/envs/thesis/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lars/miniconda3/envs/thesis/lib/python3.10/site-packages/escnn/nn/modules/conv/r2convolution.py", line 208, in forward
    _filter, _bias = self.expand_parameters()
  File "/home/lars/miniconda3/envs/thesis/lib/python3.10/site-packages/escnn/nn/modules/conv/rd_convolution.py", line 269, in expand_parameters
    _filter = self.basisexpansion(self.weights)
  File "/home/lars/miniconda3/envs/thesis/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lars/miniconda3/envs/thesis/lib/python3.10/site-packages/escnn/nn/modules/basismanager/basisexpansion_blocks.py", line 354, in forward
    _filter[
RuntimeError: Index put requires the source and destination dtypes match, got Float for the destination and Half for the source.
```
Which seems to suggest that at some part in the code a tensor is created with hardcoded Float dtype, which is not compatible with the Half dtype. I have spent a little bit of time trying to find where this happens, but I haven't found the exact part yet.

Note: Uncommenting lines 29 through 35 is an example where it does work, since a uniform field type is used there. 
In this particular example, it would make more sense to use the uniform field type anyways. But for cases where you'd want a non-uniform field type this issue could be troublesome.

**Comment by Gabri95** [comment]
Hi @LVeefkind ,

Thanks a lot for spotting this issue!

The problem is that, in the non-uniform case, I preallocate the tensor with the full filter and then fill its blocks iteratively, but AMP infers a different dtype for individual blocks and the preallocated tensor.

I fixed it by allocating the full tensor in a lazy way, i.e. I wait for the first block to be computed and manually use the dtype of this block to allocate the full tensor.
This solution seems to work for me, but I can imagine it might break if two blocks are assigned two different dtypes by AMP.
At the moment, I don't see a reason why this should happen, though.

Please, let me know if you experience a similar problem.

I will soon push a commit to fix this and upload the new version on pypi tomorrow.

Thanks again,
Gabriele
