### ISSUE TITLE
type.representations are tuple or list, combinations break

### ISSUE THREAD

**Issue by pimdh** [QUVA-Lab/escnn#8]
Hi @Gabri95, thanks for making this nice library ;).

I've managed to break it. You seem to be using `type.representations` sometimes a tuple and sometimes a list. When one tries to combine those, it breaks, because python is fine with list+list and tuple+tuple, but doesn't like tuple+list.

```python
g = so3_group()
rho = G.irrep(0)+G.irrep(1)
gspace = no_base_space(G)
in_type = gspace.type(rho)
subgroup_id = (False, -1)  # identifies the SO(2) subgroup of rotations around the Z axis
h, _, _ = g.subgroup(subgroup_id)
gspace_h = no_base_space(h)
in_type_h = in_type.restrict(subgroup_id)
radial_type = gspace_h.type(h.irrep(0))
print(type(in_type.representations))
print(type(in_type_h.representations))
print(type(radial_type.representations))
in_type_h+radial_type
```
Gives error:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-71-4cf0c77ed4a3>", line 13, in <module>
    in_type_h+radial_type
  File "/usr2/pim/.local/lib/python3.8/site-packages/escnn/nn/field_type.py", line 436, in __add__
    return FieldType(self.gspace, self.representations + other.representations)
TypeError: can only concatenate list (not "tuple") to list
```
I'm working around this by adding:
```python
in_type_h.representations = tuple(in_type_h.representations)
```
So no rush in fixing this. Just wanted to let you know.

Cheers,
Pim

**Comment by Gabri95** [comment]
Problem solved, thanks a lot for spotting this issue!
